CAR_LIST = [
    {"spawn_name": "npolstang", "tier": "S", "subclass": "police > S"},
    {"spawn_name": "npolvette", "tier": "S", "subclass": "police > S"},
    {"spawn_name": "demon_MrF", "tier": "A", "subclass": "MUSCLE"},
    {"spawn_name": "demonicbuffo", "tier": "A", "subclass": "MUSCLE"},
    {"spawn_name": "DominatorCustom", "tier": "A", "subclass": "MUSCLE"},
    {"spawn_name": "fastPrimo", "tier": "A", "subclass": "MUSCLE"},
    {"spawn_name": "MangoliaForest9", "tier": "A", "subclass": "MUSCLE"},
    {"spawn_name": "MostwantedGauntlet", "tier": "A", "subclass": "MUSCLE"},
    {"spawn_name": "tiofox", "tier": "A", "subclass": "MUSCLE"},
    {"spawn_name": "ZeYumari", "tier": "A", "subclass": "MUSCLE"},
    {"spawn_name": "bountyhuntah", "tier": "A", "subclass": "OFF ROAD"},
    {"spawn_name": "bronbyv", "tier": "A", "subclass": "OFF ROAD"},
    {"spawn_name": "dubstas500", "tier": "A", "subclass": "OFF ROAD"},
    {"spawn_name": "henduneloader", "tier": "A", "subclass": "OFF ROAD"},
    {"spawn_name": "TitanQueenZ", "tier": "A", "subclass": "OFF ROAD"},
    {"spawn_name": "tortaslammer", "tier": "A", "subclass": "OFF ROAD"},
    {"spawn_name": "npolchar", "tier": "A", "subclass": "police > A"},
    {"spawn_name": "npolvic", "tier": "A", "subclass": "police > A"},
    {"spawn_name": "POLCHAR", "tier": "A", "subclass": "police > A"},
    {"spawn_name": "polcom", "tier": "A", "subclass": "police > A"},
    {"spawn_name": "polct", "tier": "A", "subclass": "police > A"},
    {"spawn_name": "polfoc", "tier": "A", "subclass": "police > A"},
    {"spawn_name": "sastgt17", "tier": "A", "subclass": "police > A"},
    {"spawn_name": "polrap", "tier": "A", "subclass": "police > A OFFROAD"},
    {"spawn_name": "500WSLB", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "benefactor205", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "burgerstang", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "Cabrienne333", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "Cognoslas20", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "cometgt310", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "cons19", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "DBA1buffo", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "Esperantoikx3", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "Exemplarprime001", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "flyingenus24", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "GODz21Revo", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "GODz21sentinel", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "goldenGtime", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "issicm", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "Jayalove", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "jugularest", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "kbeast", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "mans22oracle", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "milk1500wb", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "niobehyperkit3", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "Obey10FBa", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "oracle340", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "oracledum", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "Prairria10", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "Princess17", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "rhinoheartero", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "ricos", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "SpiciMobile", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "topG20", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "tunacam", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "uberaclegg8", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "ubermacht7race", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "ubermatchtbt", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "ubermatchttopspec", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "vanzoracle40", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "VectreFX322", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "wmbd2s", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "XSentinel435", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "zlaybach_BE", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "zlayparagon", "tier": "A", "subclass": "SEDAN"},
    {"spawn_name": "AstroRyan", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "bansheebun", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "bbjester", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "bestiabeast", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Bestiaoppo", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "bobert", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "boopra", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "bovenaan", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "britemplar", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "burgerline", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Caymant", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "chromelegy", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Cindarella8", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "CometScade", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "CometstarxT", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Cometturboz", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "CoqOSDB", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "croquette7", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "d1jester", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "DBallen21M3", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Dewbauchbyv", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "dewspecter", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Drafter20", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "dragoncar", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "elegy50", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Elegyab", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "elegyGzilla", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "elegyhycadeRH8", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "elegymo17", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "ElegyR35BT", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Elegyspecx", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "elegyssar", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "elegyxtr", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "ETR1c", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "ETRr3", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "euros8hachz", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "EuroZ20T", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "evolution11z", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "fdbanshee", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Fexter200", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "foreignvet", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "foureighteight", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "fq2pswbsd", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "furia200ultra", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "garcia", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "GODzFD", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "grant4beast", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "gtruras", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "gtz", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "GtzAbflug", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Hanslillekanin", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "hardsentinelfour", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "hourjesthur", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "hubelegy69", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "hycadelegycust", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "hycader36", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "hykarincade", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "hykarinGZ", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "hypElegyRH8core", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "hyperkitNiobe8", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "hyspiceade", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "i8dy", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "ikx3carbonizzare", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "ikx3gt", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "ikxelegy24", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "InveteroKane", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "italilt21", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "italiRSX855", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "itsfkingeaster", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "jay31", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "jccist1", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "jcraw", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "jesterk5", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "jestersam", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "JesterUltraZW", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "jesterup", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "karinvar", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "KurumaWB", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "lfinf", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "LiberaGmod", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "LunaBanshee", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Lunatica", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "madelegyXR", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "mansa_milly", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "mansZion", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "MaPetiteBelle", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Marcotteroracle", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Mooncat", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "nelegytune", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "NightmareQueen", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "OIIAOIIA", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Omnishycade", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "oracle2wb", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "oracle5touring", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "oracleadro82", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "OracleShade", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "p11ts", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Pariahspec", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "PegususGT", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Pfister811XT", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Pfisterforce", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "priskdrafter", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "razerajester", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "ReblaRevt", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Revoltervarisc", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "RobXLuna", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Rodiodra", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "rrfr60x", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "rritaliagtox", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "rs5mafia", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "sclelegy", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Sentiflug", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Sentiwellicade", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "SHADY35", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Sharkscent", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "sigma36x", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "slugmobile", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Snowflake", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "StarvectreZ20", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "sultanimpvaris", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Suranobs", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "swl", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Tecomet111", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "teenspirit", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "tiogreyseries", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "ToZebee", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Turismoaggio22", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "v10", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Vaccahycade", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "vbbpxxc", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "vectre13", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "vectretunazR", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "Venominator", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "venuumtt", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "vxss", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "WideBanshee", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "xarmas7", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "zionshark", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "zlay_ebisu35", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "zlay_elegy", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "zlay_fair", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "zlay_gold", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "zlay_gtz2077", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "zlay_infinite", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "zlay_kuruma", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "zlay_mostwanted", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "zlay_shadow", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "zlay_zellegy", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "ZR380FutureSH", "tier": "A", "subclass": "SPORT"},
    {"spawn_name": "blsbnsport", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "comets21", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "CookieSentinel", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "elegyhykitwf", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "elerecu", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "elitejester1", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "eurostune", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "eurosxtreme", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "Euroszdk", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "fair7", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "Feltbullet", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "Groaudia", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "Hoonie", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "jester1elite", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "mancometty", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "morackcorquette", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "na1rk", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "nsfw", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "Numbrami92", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "pfisterevolution", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "playaturbocoquette", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "reCoquette5", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "verysoupie", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "yury", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "zlay_300", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "zlay_calico2", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "zlay_CalicoV2", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "zlay_comet", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "zlay_fake", "tier": "A", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "autobio", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "ballerflug", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "discomposurethemysterymachine", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "DMxrebla", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "dubsta219", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "Dubsta4x4byv", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "enusgast", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "escaladesport", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "Everontasser", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "fpaceprior", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "gatorflug", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "gatorhawk18", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "GCGranger", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "gcmryback", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "GoDBaller4TTD", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "GODzESKYVWB", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "gresleybyv", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "HycadeAleutian", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "ikx3Toros23", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "Jequeep", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "jubilee2", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "kairango", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "kietdepzai", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "LuradoXXT", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "mansCavalcade", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "Mobrebla", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "moglemansory", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "norgingot", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "oparus89", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "oracle53", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "Pegassivid", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "queenballer", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "reblaprior21custom", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "redgresley", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "SakuraSentinel", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "SchafoneOR", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "sclkuz", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "TewPaq202", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "tgburgerreg", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "toros19nov", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "toros2019", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "torosflug", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "toroslb22", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "torosspeedster", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "trackhawk2ncs", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "tunertoros", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "Uberbonez", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "ubermachterD42", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "urusvennum", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "vapidwidebody", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "vnmtoros", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "VOITURE", "tier": "A", "subclass": "SUV"},
    {"spawn_name": "blistawedge", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "dinkaff", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "dinkasunspot", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "fatissi15", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "fnfLivic", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "gcmclub8r", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "gstkansj1", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "hblrasbo", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "ikx303", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "jcv6", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "MrSpider20", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "naveg6", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "organ", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "postludeluxe", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "squirrelnuts", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "ts3", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "Xtremeclub", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "Zanemobile2020", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "ZaneSuper", "tier": "B", "subclass": "COMPACT"},
    {"spawn_name": "cjiggler300", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "dgauntlet15", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "dominator6502", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "DominatorWB", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "Dominatorwide", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "EVXbuffalo", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "EVXbuffoHell", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "Fadejstcura", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "forgotten5020", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "foxgauntlet", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "Gatatoshade2", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "gauntlet1000", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "gauntletg500", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "gauntletzom", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "genf", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "GODzCAT", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "GODzlbvert", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "GODzSUELORADO", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "hatestang", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "helltampa", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "hs", "tier": "B", "subclass": "MUSCLE"},
    {"spawn_name": "npolexp", "tier": "B", "subclass": "police > B"},
    {"spawn_name": "npoltaur", "tier": "B", "subclass": "police > B"},
    {"spawn_name": "polchartr", "tier": "B", "subclass": "police > B"},
    {"spawn_name": "npoltrx", "tier": "B", "subclass": "police > B OFFROAD"},
    {"spawn_name": "poltah", "tier": "B", "subclass": "police > B OFFROAD"},
    {"spawn_name": "poldur", "tier": "B", "subclass": "police > B SUV"},
    {"spawn_name": "RHX8laselegy", "tier": "B", "subclass": "SPORT"},
    {"spawn_name": "lbw33", "tier": "B", "subclass": "SPORT CLASSIC"},
    {"spawn_name": "schwarzer2", "tier": "Misc", "subclass": "Lore Friendly Car Pack > 6STR"},
    {"spawn_name": "tempesta2", "tier": "Misc", "subclass": "Lore Friendly Car Pack > 6STR"},
    {"spawn_name": "galaxy4x4", "tier": "Misc", "subclass": "store-vehicles"},
    {"spawn_name": "bansheeturbo", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "escdinka650r", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "Esmeralda10", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "exc530", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "fat264", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "firmbike", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "GODz17HDSGBAGGER", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "GODz17HDSGBAGGERM", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "godzdayBati", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "godzdinka1000rr", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "hakuchoudrag", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "HDIron883", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "hellcycle", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "lst2", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "moomoo", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "Nehe2ere", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "pbshinobisquid", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "penidinka", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "shinobin2", "tier": "Special", "subclass": "MOTORCYCLE"},
    {"spawn_name": "Sweepingwind", "tier": "Special", "subclass": "SPONSORSHOP"},
]
